name: clavis
description: "Clavis (Latin for key) is a modular architecture library for Flutter that combines communication, routing, and configuration in larger projects."
version: 1.0.0
homepage: https://github.com/jeltou/fores

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  yaml: ^3.1.2
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

